remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
prev_next_navigation:
- bottom

# TODO Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "NASA APOD"
description: "NASA Astronomy Picture of the Day"
author:
  name: "Minerva Franco"

# Do not change the following line.
  copyright: true
